name: Check Version Consistency

on:
  push:
    branches:
      - main

jobs:
  version-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Check version consistency
      run: |
        ./scripts/ci/check_version.sh
