name: Test

on:
  pull_request:
    branches:
      - release

jobs:
  tests:
    name: "${{ matrix.tf_runner }} v${{ matrix.tf_version }} - Py${{ matrix.python }} - ${{ matrix.os || 'Ubuntu' }}"
    runs-on: ${{ matrix.os || 'ubuntu-latest' }}

    strategy:
      fail-fast: false
      matrix:
        tf_runner: ['terraform', 'tofu']
        tf_version: ['1.6', '1.7', '1.8', '1.9', '1.10', '1.11']
        python: ['3.13', '3.12', '3.11', '3.10', '3.9']
        include:
          - {name: Windows, python: '3.12', os: windows-latest}
          - {name: Mac, python: '3.12', os: macos-latest}
        exclude:
          # Remove versions not available in OpenTofu
          - { tf_runner: 'tofu', tf_version: '1.10' }
          - { tf_runner: 'tofu', tf_version: '1.11' }

    steps:
      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1
        if: matrix.tf_runner == 'tofu'
        with:
          tofu_version: ${{ matrix.tf_version }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        if: matrix.tf_runner == 'terraform'
        with:
          terraform_version: ${{ matrix.tf_version }}

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          allow-prereleases: true
          cache: 'pip' # Cache dependencies installed by pip (including hatch itself)
          cache-dependency-path: 'pyproject.toml' # Key the cache on your project file

      # --- Install Hatch ---
      - name: Install Hatch
        run: pip install hatch

      # Although 'hatch run' can often work with editable installs,
      # explicitly building first ensures your package *is* buildable
      # and catches packaging errors early.
      - name: Build package
        run: hatch build

      # 1. Activate/prepare the 'test' environment (installing deps from pyproject.toml)
      # 2. Execute the script named 'run' defined in [tool.hatch.envs.test.scripts]
      # 3. Pass any arguments after '--' to the script (pytest in this case)
      # 4. Environment variables like VINERY_RUNNER are passed through.
      - name: Run tests using hatch
        run: |
          VINERY_RUNNER=${{ matrix.tf_runner }} hatch run test:run -- -vs